backend:
  name: github
  repo: milton0999/web-doctora-astro # Cambiado de username/repo a tu repo real
  branch: main
  base_url: https://centromedicogonzalitos.milcoms.org # Tu dominio personalizado
  auth_endpoint: api/auth # Apunta a tu carpeta functions/api

media_folder: public/img/servicios # Donde se guardarán las fotos
public_folder: /img/servicios

collections:
  - name: 'servicios'
    label: 'Servicios y Estudios'
    folder: 'src/content/servicios' # Carpeta que ya tienes creada
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Nombre del Estudio', name: 'title', widget: 'string' }
      - { label: 'Imagen del Estudio', name: 'image', widget: 'image' } # AQUÍ SUBE LA FOTO
      - { label: 'Descripción breve', name: 'description', widget: 'string' }
      - { label: 'Contenido Detallado', name: 'body', widget: 'markdown' } # AQUÍ VA EL TEXTO DEL WAYBACK